### ISSUE TITLE
Error in deploying Azure Private WAN

### ISSUE THREAD

**Issue by rajpaz** [MitchellGulledge/Meraki-vWAN#15]
Hello Mitchell, 

I am getting the following error code and I am not sure how to proceed. I have looked at my installation and it seems okay. 

![Screen Shot 2020-09-30 at 7 27 14 AM](https://user-images.githubusercontent.com/10697135/94698656-6121a900-02ee-11eb-90a5-38090f3a5306.png)

Since, I have created only one hub, I am not sure what the function is looking for. 
thanks in advance for any help you can provide. i have created a case but they have been unable to help. 

best

Rajesh

**Comment by MitchellGulledge** [comment]
Rajesh,

Apologies for the delay. Looking at the code looks like you are getting stopped here:

        # Check if VWAN Hubs in scope exist; if not log an error the hub doesn't exist
        hubs_exist = check_vwan_hubs_exist(virtual_wan, tagged_hubs)
        if(not hubs_exist):
            logging.error("Not all Virtual WAN hubs exist, please ensure all hubs are created.")
            return

Here is the function being called:

def check_vwan_hubs_exist(virtual_wan, tags):

    for tag in tags:
        if tag.lower() not in (vwan_hub['id'].rsplit('/', 1)[-1].lower() \
                                for vwan_hub in virtual_wan['properties']['virtualHubs']):
            return False

    return True

Can you please share a snippet of your configured Virtual WAN Hubs in the Azure Portal?

**Comment by MitchellGulledge** [comment]
@rajpaz can you confirm that you were able to get this issue resolved? I am going to close this for inactivity. Please feel free to reach out or reopen if you see the issue at all in the future :)
