### ISSUE TITLE
Error deploying VPN for the first time

### ISSUE THREAD

**Issue by Tony-FCTG** [MitchellGulledge/Meraki-vWAN#21]
Hello.

I've run through the document and believe all the steps have been followed.
The Azure app can see the tags on the Meraki networks.
VPNs fail to be created with the following error/s.
Any help and advise will be appreciated.

Result: Failure Exception: KeyError: 'subnets' Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 355, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 542, in __run_sync_func return func(**params) File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 868, in main privsub = ([x['localSubnet'] for x in va['subnets'] if x['useVpn'] is True])

Executed 'Functions.Meraki-VWAN-Automation' (Failed, Id=0112d44b-7a73-4985-a901-c65d2f60b8d3, Duration=43133ms)

**Comment by MitchellGulledge** [comment]
Really sorry to hear that, can you paste a screenshot or confirm that the branch that you are connecting to vWAN has a subnet that is in side VPN? For instance under the site to site VPN settings.

**Comment by Tony-FCTG** [comment]
Flight Centre (UK) Limited (Reg. No. 02937210) - Level 6 CI Tower, High Street, New Malden, Surrey KT3 4TE

**Comment by MitchellGulledge** [comment]
I was able to locate the Teleworker Gateway DC1 network for you. It appears that you still need to turn on site to site VPN for the network and click yes for the subnets you want to have reachability to Azure for.
