### ISSUE TITLE
Is it possible to run multiple scripts and meraki organizations?

### ISSUE THREAD

**Issue by Tony-FCTG** [MitchellGulledge/Meraki-vWAN#22]
Hi.
This isn't an issue rather a query.
We have a situation where we have two Meraki organizations that need to connect to the same Azure vWAN.
Do you see any issues with creating two deployments of the automation script in Azure and setting each to different meraki organizations?

**Comment by MitchellGulledge** [comment]
No not at all, this should be fine :) Apologies for the delay.

**Comment by MitchellGulledge** [comment]
going to close this out, but feel free to re open if you have any additional ques :)
