### ISSUE TITLE
Python should be updated to the latest version for your function app

### ISSUE THREAD

**Issue by Tony-FCTG** [MitchellGulledge/Meraki-vWAN#25]
Azure Security Center - Recommendations is suggesting Python needs updating.
Can you advise what we should do with this recommendation?
Can Python be updated on the app?

![Screenshot 2021-03-05 150858](https://user-images.githubusercontent.com/77326675/110133929-c65d5700-7dc4-11eb-8580-60682f41b1b4.png)

**Comment by JackStromberg** [comment]
This policy is looking for the Function to run at Python v3.9, which is still in Preview.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-python

The template deploys the latest version of Python v3.8, so this can be exempt until v3.9 is GA.

**Comment by Tony-FCTG** [comment]
Flight Centre (UK) Limited (Reg. No. 02937210) - Level 6 CI Tower, High Street, New Malden, Surrey KT3 4TE
