### ISSUE TITLE
Azure Function keeps failing

### ISSUE THREAD

**Issue by ppetchged** [MitchellGulledge/Meraki-vWAN#35]
Hello Team,

The Azure Function keeps failing. I could not get it to work. I tried v1 or the one from Meraki's site. Same issue.

2021-06-24 16:45:02.024
Result: Failure Exception: IndexError: list index out of range Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 398, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 602, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 974, in main meraki_vpn_failover() File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 88, in meraki_vpn_failover network_id_list.append(org_network_response[0]['id'])
Error

**Comment by MitchellGulledge** [comment]
This is strange, is this a newly deployed function app? If so, we just made a few commits and updated the button to point to a new branch of code v1API2 here: https://documentation.meraki.com/MX/Deployment_Guides/Cisco_Meraki_MX_Branch_to_Azure_Virtual_WAN_Deployment_Guide 
The change was pushed yesterday. 
Additionally, it appears that this is a issue with failing over the Meraki VPN and how I might be indexing a response org_network_response[0]['id'] might not need that [0]. Might be a scenario where the indexing is not needed but would like to confirm the branch you are on first.

**Comment by MitchellGulledge** [comment]
Is this the same issue that is recorded here: https://github.com/MitchellGulledge/Meraki-vWAN/issues/27 is the status of your tunnel down and we do not have vpn events in the event log?

**Comment by ppetchged** [comment]
Yes.This is brand new deployment. I tried the one from this link https://documentation.meraki.com/MX/Deployment_Guides/Cisco_Meraki_MX_Branch_to_Azure_Virtual_WAN_Deployment_Guide and the one from GitHub

**Comment by ppetchged** [comment]
> Is this the same issue that is recorded here: #27 is the status of your tunnel down and we do not have vpn events in the event log?

Correct. No events in the event log.

**Comment by MitchellGulledge** [comment]
Ah, if you send some pings from the MX in dashboard to any IP that is in the Azure subnets do we see the tunnel brought up and do the errors stop? This is likely just due to the fact that there are no VPN events in the event log and I am trying to index something that doesnt exist because the tunnel isnt brought up. Which is something that should be fixed ASAP but may not be business impacting etc

**Comment by ppetchged** [comment]
Ping did not help. I switched to the function from this link https://documentation.meraki.com/MX/Deployment_Guides/Cisco_Meraki_MX_Branch_to_Azure_Virtual_WAN_Deployment_Guide 

2021-06-24 18:50:36.869
Result: Failure Exception: IndexError: list index out of range Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 398, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 602, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 974, in main meraki_vpn_failover() File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 123, in meraki_vpn_failover event_data = events_response_data[-1]['eventData']
Error


2021-06-24 18:50:36.870
Executed 'Functions.Meraki-VWAN-Automation' (Failed, Id=6fbeb939-a4e8-4446-b2e9-b19ef62c2f77, Duration=36851ms)
Error


2021-06-24 18:50:36.878
Result: Failure Exception: IndexError: list index out of range Stack: File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 398, in _handle__invocation_request call_result = await self._loop.run_in_executor( File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 602, in _run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = function(**args) File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 974, in main meraki_vpn_failover() File "/home/site/wwwroot/Meraki-VWAN-Automation/__init__.py", line 123, in meraki_vpn_failover event_data = events_response_data[-1]['eventData']
Error

**Comment by MitchellGulledge** [comment]
Can you send me the mac/serial for your Meraki box? Is the tunnel coming up at all? I think the script is looking for event log data that may not exist, but want to confirm

**Comment by ppetchged** [comment]
We have a HA pair here is the primary one Q2KN-AACV-UBXR, No Tunnel coming up.

Our Firmware is 
Current version: MX 15.42

**Comment by ppetchged** [comment]
and just want to make sure. I don't need to create a VPN site in Virtual HUB , Correct ? The script will create the VPN site for me.

**Comment by MitchellGulledge** [comment]
The script will take care of that, but the reason this is failing is because you do not have any local subnets in your site to site vpn page selected for yes to be allowed inside the VPN. Select a subnet as yes and then send some pings (this is why there were not any logs in the first place) and you should be good to go :) (this explains why there were no vpn logs in the event log showing the error you pasted above)

**Comment by ppetchged** [comment]
You mean this part, Correct ? 

![image](https://user-images.githubusercontent.com/74633308/123322254-eab28000-d4e8-11eb-8464-7bc727b3a3c3.png)

**Comment by MitchellGulledge** [comment]
yes :)

**Comment by ppetchged** [comment]
> yes :)

No luck. I enabled subnets needed to be on VPN. Tried ping to another site and still no events. I will wait for a bit then.

**Comment by ppetchged** [comment]
Still no VPN event Logs.

**Comment by ppetchged** [comment]
and when I tried run this code manually. I got 500 error. I'm run our of ideas here :-(

![image](https://user-images.githubusercontent.com/74633308/123327044-ceb1dd00-d4ee-11eb-87f1-634031f07ccb.png)

**Comment by MitchellGulledge** [comment]
taking some captures now, can you confirm the site is there with the correct public IPs in the vWAN dashboard?

**Comment by MitchellGulledge** [comment]
can we create a local vlan called test with an unused IP space that is in vpn? (not a static route) I am. not seeing interesting traffic going in the tunnel on the Meraki and dont see phase 1 packets going out. And since we cannot source a ping from a static route it will not match the IKEv2 traffic selectors for the IPsec config. I worry that this might be the root problem

**Comment by ppetchged** [comment]
> test

OK. I got a new VLAN created and have a computer connected to this VLAN and pinging the VPN gateway in Azure. The public IPs of AZure VPN Gateway are correct.

**Comment by MitchellGulledge** [comment]
Hmm okay now I can see some ISAKMP traffic sourced from the MX64 but nothing coming back from Azure. 
<img width="1390" alt="Screen Shot 2021-06-24 at 2 59 11 PM" src="https://user-images.githubusercontent.com/61255163/123337966-e1331300-d4fc-11eb-82c3-1c960429b1f1.png">
Can you confirm we have the correct private subnets in the azure customer gateway config? Something is very strange here :(

**Comment by MitchellGulledge** [comment]
Like I can see us trying to initiate a tunnel now which I couldnt before after generating interesting traffic so definately progress but now I dont see the ISAKMP traffic from the vWAN hub

**Comment by MitchellGulledge** [comment]
Looks like your tunnel is up now, did you have to do anything to remediate the function or did it correct after some time?

**Comment by MitchellGulledge** [comment]
Hello, wanted to check in and verify whether or not you are still seeing issues with the Azure function?

**Comment by MitchellGulledge** [comment]
I am going to close this case, feel free to reopen if you encounter any further issues :)
